package com.compass.digitalbank.domain.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    INVALID_TRANSFER,
    INACTIVE_ACCOUNT,
    EMAIL_ALREADY_USED,
    FORBIDDEN_OPERATION,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    DATA_CONFLICT,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR
}
